### PR TITLE
update chrome devtools settings screencap to current

### PR DESCRIPTION
**Pull request by morenoh149**
the screencap linked to was out of date. Uploaded a current one.

### CODE REVIEW

**Comment by SomeoneWeird** [comment]
Where are you seeing this? I'm running chrome dev and my devtools still look like the old image.

**Comment by morenoh149** [comment]
I'm running chrome v44 on osx. Instead of `Causes` I see `Stacks`.
screenshot 2015-08-21 01 29 55

**Comment by SomeoneWeird** [comment]
I'm running v46 dev, maybe it's changed in the newer versions?

screen shot 2015-08-21 at 4 48 12 pm

**Comment by morenoh149** [comment]
ah okay

**Pull request closed without merging**
